FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./

RUN npm ci

COPY . .

ARG VITE_AUTH_URL=http://localhost:9000
ARG VITE_CLIENT_ID=myclientid
ARG VITE_REDIRECT_URI=http://localhost:5173/callback
ARG VITE_POST_LOGOUT_URI=http://localhost:5173/
ARG VITE_SCOPE="read openid"
ENV \
  VITE_AUTH_URL=$VITE_AUTH_URL \
  VITE_CLIENT_ID=$VITE_CLIENT_ID \
  VITE_REDIRECT_URI=$VITE_REDIRECT_URI \
  VITE_POST_LOGOUT_URI=$VITE_POST_LOGOUT_URI \
  VITE_SCOPE=$VITE_SCOPE

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80